-- 코드를 입력하세요
SELECT BOOK.AUTHOR_ID,AUTHOR.AUTHOR_NAME,BOOK.CATEGORY,SUM(PRICE*SALES) AS TOTAL_SALES
FROM BOOK,AUTHOR,BOOK_SALES
WHERE BOOK.BOOK_ID=BOOK_SALES.BOOK_ID
AND BOOK.AUTHOR_ID=AUTHOR.AUTHOR_ID
AND SALES_DATE LIKE '2022-01-%'
GROUP BY BOOK.AUTHOR_ID,CATEGORY
ORDER BY AUTHOR_ID,CATEGORY DESC